name: kpop
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow
  - kpop
  - bash >=4.4.18
  - r-tidyverse
  - r-ape
  - r-phangorn
  - r-ggplot2
  - r-ggrepel
  - r-plot3D
  - r-codetools
  - bioconductor-ggtree
  - bioconductor-ggtreeextra
  - megahit
  - flash
  - lastz
  - seqkit
  - sra-tools >=3.1.1
  - trim-galore

